GO_EASY_ON_ME = 1

TWEAK_NAME = Hooper
Hooper_FILES = Hooper.m
Hooper_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
Hooper_FRAMEWORKS = UIKit

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
